name: Build, Release, and Deploy Resume to GitHub Pages

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: write  # Grant write permission to push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Git for committing changes
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Extract the branch or tag name
      - name: Get Reference
        id: get_ref
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "REF_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "REF_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi

      # Step 4: Install Minimal LaTeX
      - name: Install Minimal LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk

      # Step 5: Build LaTeX Resume
      - name: Compile LaTeX Resume
        run: |
          latexmk -pdf -interaction=nonstopmode resume.tex
          latexmk -c

      # Step 6: Upload PDF Artifact (optional, used for releases)
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-${{ env.REF_NAME }}
          path: resume.pdf

      # Step 7: Prepare Directory for GitHub Pages
      - name: Prepare Directory for GitHub Pages
        run: |
          mkdir -p public/${REF_NAME}
          mv resume.pdf public/${REF_NAME}/resume.pdf

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
